// MT4 compatible symbol mapping
exports.symbolMapping = {
  'BTCUSDT': 'BTCUSD',
  'ETHUSDT': 'ETHUSD',
  'BNBUSDT': 'BNBUSD',
  'XRPUSDT': 'XRPUSD',
  'ADAUSDT': 'ADAUSD',
  'DOGEUSDT': 'DOGEUSD',
  'SOLUSDT': 'SOLUSD',
  'DOTUSDT': 'DOTUSD',
  'LINKUSDT': 'LINKUSD',
  'UNIUSDT': 'UNIUSD',
  'MATICUSDT': 'MATICUSD',
  'AVAXUSDT': 'AVAXUSD',
  'SHIBUSDT': 'SHIBUSD',
  'LTCUSDT': 'LTCUSD',
  'ATOMUSDT': 'ATOMUSD'
};